grafana:
  envValueFrom:
    GF_SMTP_USER:
      secretKeyRef:
        name: grafana-smtp-secret
        key: user
    GF_SMTP_PASSWORD:
      secretKeyRef:
        name: grafana-smtp-secret
        key: password

  grafana.ini:
    smtp:
      enabled: true
      host: smtp.gmail.com:587
      user: $__env{GF_SMTP_USER}
      password: $__env{GF_SMTP_PASSWORD}
      from_address: $__env{GF_SMTP_USER}
      from_name: Grafana Alerts
      startTLS_policy: OpportunisticStartTLS
