apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-rollout-demo
  namespace: staging
spec:
  replicas: 2

  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause:
          duration: 60s
      - setWeight: 100

  selector:
    matchLabels:
      app: backend-rollout-demo

  template:
    metadata:
      labels:
        app: backend-rollout-demo

    spec:
      serviceAccountName: backend-sa

      containers:
      - name: backend
        image: 622488711452.dkr.ecr.us-east-1.amazonaws.com/devops-backend:v2

        ports:
        - containerPort: 5000

        envFrom:
        - secretRef:
            name: backend-db-secret

        env:
        - name: S3_BUCKET
          value: "devops-master-lambda-trigger-bucket-622488711452"

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"